:imagesdir: chapters/requests_and_routing/images

= Requests & Routing

Webbapplikationer fungerar genom att en klient (webbläsare) kommunicerar med en server (i vårt fall Sinatra) med hjälp av protokollet HTTP.

I HTTP finns det två typer av meddelanden: HTTP *Request* och HTTP *Response*

Förenklat sker kommunikationen enligt följande: 

* En webbläsare skickar en HTTP request efter en viss _resurs_ på servern.
* Servern kollar sen om resursen finns. 
** Om resursen finns skickar servern en HTTP response med status 200 och vad nu resursen innerhåller för data (t.ex html).
** Om resursen inte finns skickar servern en HTTP response med status 404 (och eventuellt html som visar ett fint felmeddelande).
* Klienten tolkar sen responsen (t.ex ritar upp HTML på skärmen)


[NOTE] 
.Resurs
====
En _resurs_ kan vara t.ex en bild, en css- eller javascript-fil, men det kan också vara en "sida" på en site: t.ex. \https://www.fruit-o-matic.com**/fruits** eller \https://fruit-o-matic.com**/fruits/apples/3/** där `/fruits` respektive `/fruits/apples/3` är resursen. En resurs är "R:et" i `URL`: Universal *Resource* Locator.
==== 

En webbapplikation skickar _aldrig_ information utan att den blivit ombedd. För att skicka information till en webbläsare måste webbläsaren först fråga efter informationen. Detta innebär att all kommunikation mellan en webbserver och en webbläsare alltid börjar med en `Request` från en klient (webbläsaren) och slutar med en `Response` från servern.


[discrete]
== Sekvensdiagram

För att beskriva hur en HTTP Request/Response går till brukar man använda https://en.wikipedia.org/wiki/Sequence_diagram[sekvensdiagram]

Sekvensdiagram beskriver hur olika _komponenter_ (t.ex webbläsare och sinatra-server) skickar "meddelanden" till varandra. Meddelanden visas som text ovanför pilar som går från sändare till mottagare.

.Ett utförligt sekvensdiagram som beskriver en lyckad request efter resursen /fruits
[mermaid,theme=neutral]
....
sequenceDiagram
    participant User
    participant Browser
    participant Rack
    participant Sinatra
    User->>Browser: Go to <br>'https://fruit-o-matic.com/fruits'
    Browser->>Rack: HTTP Request <br> 'GET /fruits HTTP/1.1...'
    Rack->Sinatra: get('/fruits')
    Sinatra-->>Sinatra: Match against routes in app.rb
    Sinatra-->>Sinatra: Render template fruits/index.erb
    Sinatra->>Rack: 200, '!doctype html <html><head>...'
    Rack->>Browser: HTTP RESPONSE <br> 'HTTP/1.1 200 OK...'
    Browser-->>Browser: Render Page
    Browser->>User: Rendered Page
    User-->>User: Wow, such beautiful fruits!
....

Sekvensdiagrammet ovan är onödigt detaljerat, i fortsättningen kommmer vi inte visa de komponenter vi ändå inte har kontroll över. Ett sekvensdiagram för motsvarande aktivitet ser då ut som nedan:

.Ett mer kompakt sekvensdiagram som beskriver en lyckad request efter resursen /fruits
[mermaid,theme=neutral]
....
sequenceDiagram
    participant Client
    participant App
    Client->>App:  GET /fruits
    App-->>App: Match route
    App-->>App: Render template
    App->>Client: 200, resource
....

Det finns två typer av `HTTP Requests` som en webbläsare kan skicka (det finns egentligen fler, men det är bara dessa två som är relevanta för kursen Webbserverprogrammering 1):

[discrete]
==== HTTP GET Request

En `HTTP GET Request` ber om att få en specifik `resurs` på servern, men kan inte skicka med någon data till servern.

[discrete]
==== HTTP POST Request

En `HTTP POST Request` skickar data (från t.ex. ett HTML-formulär) till servern.


[discrete]
== Routing

Eftersom en webbserver aldrig gör något om den inte fått en `Request` är Requests centrala i en Sinatra-applikation.

I `app.rb` skrivar man sina _routes_, dvs regler som bestämmar vilka resurser som finns på servern och vad den ska göra om den får en HTTP Request (GET eller POST) till en specifik resurs.

[source, ruby,linenums]
.app.rb
----
class App < Sinatra::Base <1>

  get '/' do <2>
    erb :index
  end

  get '/fruits' do <3>
    erb :'fruits/index'
  end

end
----
<1> Talar om att filen innehåller en Sinatra-applikation.
<2> Konfigurerar en `Route` för resursen "/"
<3> Konfigurerar en `Route` för resursen "/fruits"

När en Sinatra-applikation tar emot en request från en klient söker den efter en _route_ som matchar requestens _verb_ (`GET` eller `POST`) och dess resurs (t.ex `/fruits`). Koden i första routen som matchar kommer att köras, och resultatet läggs i ett `HTTP Response` och skickas tillbaks till klienten som skickat Requesten.

Man kan låtsas att routes i en Sinatra-app fungerar som en lång if-elsif-else-sats, enligt nedan:

[source, ruby,linenums]
.pseudokod som beskriver en *tankemodell* för hur routing fungerar
----
if verb == "GET" && resource == "/"
  return erb(:index)
elsif verb == "GET" && resource == '/fruits'
  return erb(:'fruits/index')
elsif File.exist?("./public#{resource}")
  return File.read("./public#{resource}")
else
  return (404, "Not Found")
end
----

Det är inte så det är implementerat _egentligen_, men tankemodellen fungerar när man ska bestämma vilka routes man ska ha och i vilken ordning i de behöver finnas i.

Det finns två typer av routes:

[discrete]
=== Statiska Routes

En statisk route innehåller inga dynamiska bitar, det vill säga, den request som kommer måste matcha *exakt* mot routen som den är skriven i Sinatra.

[source, ruby,linenums]
.Tre statiska routes
----
get '/' do <1>
  ... #Lämplig kod
end

get '/weather' do <2>
  ... #Lämplig kod
end

post '/weather' do <3>
  ... #Lämplig kod
end
----
<1> Matchar `HTTP **GET** Requests` till `/`
<2> Matchar `HTTP **GET** Requests` till `/weather`
<3> Matchar `HTTP **POST** Requests` till `/weather`

[discrete]
=== Dynamiska Routes

En dynamisk route är en route där _delar_ av routen kan skilja från den route som är skriven.
En dynamisk route skapas genom att man ersätter den bit av routen som ska vara dynamisk med ett kolon (`:`) följt av ett beskrivande ord.

[source, ruby,linenums]
.En dynamisk route
----
get '/weather/:city' do |city| <1>
  ... #Lämplig kod
end
----
<1> Matchar `HTTP **GET** Requests` till `/weather/*VADSOMHELST*/``, t.ex `/weather/goteborg` eller `/weather/oslo` eller `/weather/3`

Eftersom man antagligen vill veta vad det var för värde som låg på den dynamiska biten i requesten behöver man fånga upp den.

[source, ruby,linenums]
.En dynamisk route som faktiskt fångar upp den dynamiska **parametern**
----
get '/weather/:city' do |city| <1>
  ... #Lämplig kod
end
----
<1> Variabeln `city` innehåller nu vad som fanns på motsvarande ställe i requesten, text "goteborg", "oslo" eller "3".

[WARNING] 
.Siffror i dynamiska routes
====
Det som lagras i variabeln som fångar upp en parameter från en dynamisk route kommer **alltid** vara en sträng, även om det innehåller siffror.
Om applikationen förnväntar sig ett tal (integer) behöver man omvandla siffran till en integer med `.to_i`
==== 

[source, ruby,linenums]
.En dynamisk route med två **parametrar**
----
get '/weather/:city/temperature/:date' do |location, date| <1>
  ... #Lämplig kod
end
----
<1> När man har flera _parametrar_ i en dynamisk route mappas parametrar till variabler i den ordning de kommer. Om requesten är `GET /weather/**goteborg**/temperature/**2023-09-23**` kommer `location` innehålla `'goteborg'` och `date` innehålla `'2023-09-23'`.

[NOTE] 
.Namngivning av parametrar och variabler i dynamiska routes
====
Parametrar (`:city`) och variabler (`location`) _behöver_ inte heta likadant, men det blir ofta förvirrande om de inte gör det.
==== 

== Formulär och GET-POST-Redirect-Cykeln

Formulär skickar data via `POST`-requests. Men en `POST`-request ska inte användas för att _visa_ data - det är vad `GET`-requests är till för.

För att visa resursen som skapats när en användare skickat in data via ett formulär måste man därför säga till användarens webbläsare vart den ska ta vägen (dvs göra en `GET`-request till) efter servern behandlat datan.

Detta görs genom att servern, efter den behandlat datan från formuläret, skickar tillbaks en `Response` som talar om vart webbläsaren ska skicka en `GET`-request. Webbläsaren skickar sen automagiskt en `GET`-request dit servern specificerat.

[mermaid,theme=neutral]
.GET-POST-Redirect-cykeln i ett Sekvensdiagram
....
sequenceDiagram
    participant Client
    participant App
    Client->>App:  GET /fruits
    App-->>App: Match route
    App-->>App: Render template (with form)
    App->>Client: 200, resource (containing form)
    Client-->>Client: Fills out form
    Client->>App: POST '/fruits' (Submits form with form data)
    App-->>App: Match route
    App-->>App: Use form data (send to database?)
    App->>Client: 302, redirect, "/fruits/<<id of new fruit>>"
    Client->>App: GET /fruits/<<id of new fruit>>
    App-->>App: Match route
    App-->>App: Talk with DB, render template 
    App->>Client: 200, resource
....

[mermaid,theme=neutral]
.GET-POST-Redirect-cykeln som ett flödesschema
....
flowchart TD

id0[Client requests resource]
id1[Server renders resource with form]
id2[Client fills out and submits form]
id3[Server processes data from form]
id4[Server sends redirect response]
id5[Client requests redirected resource]
id0 --> id1
id1 --> id2
id2 --> id3
id3 --> id4
id4 --> id5
id5 --> id1
....

== Formulärbehandlande routes i Sinatra

Givet följande formulär som skickas in:

[source, html, linenums]
----
<form action='/fruits' method="POST">
  <input type='text' name="fruit" placeholder="Fruit name"></input>
  <input type='number' name="rating"></input>
  <button type='submit'>Create new fruit rating</button>
</form>
----

För att ta emot datan från formuläret i Sinatra behöver vi skapa en route som matchar formulärets `method` och `action` - i det här fallet `POST` och `/fruits`.

[source, ruby,linenums]
.Exempel på en route som behandlar data från formulär
----
post '/fruits' do  <1>
  name = params['fruit'] <2>
  rating = params['rating'].to_i <3>
  query = 'INSERT INTO fruits (name, rating) VALUES (?,?) RETURNING id'
  result = db.execute(query, name, rating).first <4>
  redirect "/fruits/#{result['id']}" <5>
end
----
<1> Den route som datan från formuläret skickas till. Observera `post`.
<2> Params innehåller `'fruit'` eftersom formuläret har ett input-element med `name="fruit"`
<3> All data i params är alltid strängar, om du vill ha något annat behöver man göra en typomvandling (t.ex `to_i`)
<4> Datan från formuläret behandlas på lämpligt sätt (exemplet förutsätter t.ex. att det finns en fruits-tabell)
<5> Servern skickar ett redirect-response. Klienten kommer automagiskt skicka en ny förfrågan efter resursen

[source, ruby,linenums]
.Exempel på en route man kan redirectas till (eller surfa direkt till)
----
get '/fruits/:id' do |fruit_id|  <1>
  @fruit = db.execute('SELECT * FROM fruits WHERE id = ?', fruit_id) <2>
  erb :'fruits/show' <3>
end
----
<1> En dynamisk route, som "råkar" matcha routen som redirecten ovan går till.
<2> Gör lämplig behandling av parametrarna i routen
<3> Rendera lämplig mall.

== Routes för CRUD

De allra, allra flesta webbapplikationer är så kallade CRUD-applikationer, det vill säga man kan skapa (**C**reate), visa (**R**ead), ändra (**U**pdate), och ta bort (**D**elete) olika _resurser_.

Eftersom dessa operationer (CRUD) är så vanliga finns det en standard för hur man ska jobba med dem. Det finns 7 olika _actions_ och varje _action_ och _resurs_ motsvarar en _route_ i `app.rb`

I exemplet nedan utgår vi från en app som är ett digitalt klotterplank, där resursen är `message`.

Ett message består av ett `id` och `content` (textinnehållet i meddelandet).

I appen kan vem som helst kan skriva (**C**reate) ett meddelande och meddelandena kan visas (**R**ead), ändras (**U**pdate) och tas bort (**D**elete) av vem som helst. Följande actions och routes finns för `message`, men de `routes` och `actions` som visas gäller för alla sorters resurser.

=== Action: `index` route : `/messages` method: `get`

`index` visar _en listning_ av alla förekomster av den aktuella resursen. Eventuellt kan listan vara filtrerad (t.ex skulle enbart meddelanden som tillhör den aktuella användaren kunna visas, om applikationen hade haft stöd för användare och inloggning).

[source, ruby, linenums]
.messages#index route i app.rb
----
...
  # messages#index <1>
  get '/messages' do <2>
    @messages = db.execute('SELECT * FROM messages') <3>
    erb :'messages/index' <4>
  end
...
----
<1> En kommentar som berättar vilken resurs och action routen motsvarar
<2> Routen för `index` är `/<resursens namn i plural>`
<3> Eftersom index ska visa en listning, hämtar vi alla messages från databasen
<4> För att strukturera upp våra views skapar vi en mapp per resurs, och döper vy-filen till `<action>.erb` och sparar i mappen för resursen.

[source, erb, linenums]
.views/messages/index.erb
----
<% @messages.each do |message| %>
	<p><%= message['content'] %></p>
<% end %>
----

===  Action: `show` route: `/messages/:id` method: `get`

`show` visar *en* specifik instans av den aktuella resursen, identifierad av dess `id`. Detta förutsätter att alla instanser av den aktuella resursen har ett unikt id.

[source, ruby, linenums]
.messages#show route i app.rb
----
...
  # messages#show
  get '/messages/:id' do |id| <1>
    @message = db.execute('SELECT * FROM messages WHERE id = ?', id).first <2>
    erb :'messages/show'
  end
...
----
<1> Routen för `show` är `/<resursens namn i plural>/<resursens id>`. Plocka ut `id`-parametern med `|id|`
<2> Eftersom vi alltid får en array från `db.execute` och vi bara vill ha _en_ instans i värdet tar vi det första (och enda) elementet från arrayen.

[source, erb, linenums]
.views/messages/show.erb
----
<p><%= @message['content'] %></p>
----

=== Action: `new` route: `/messages/new` method: `get`

`new` visar ett formulär för att skapa en ny instans av den aktuella resursen. Eventuellt kan man istället/även visa formuläret på `index` eller någon annanstans.

[source, ruby, linenums]
.messages#new route i app.rb
----
...
  # messages#new
  get '/messages/new' do <1>
    erb :'messages/new' 
  end
...
----
<1> Routen för `new` är `/<resursens namn i plural>/new`.

[WARNING] 
====
`new`-routen måste ligga *innan* show-routen i `app.rb`. 

Varför då?
==== 

[source, erb, linenums]
.views/messages/new.erb
----
<form action='/messages/' method='post'> <1>
  <input type='text' name='content'></input> <2>
  <button type='submit'>Send</button>
</form>
----
<1> `action` och `method` för `new`-formuläret motsvarar `create`-routen (se nedan)
<2> `name` anger namnet på parametern som skickas till `create`-routen (se nedan)

=== Action: `create` route: `/messages` method: `post`

`create` är routen new-formuläret postar datan till. Behöver sedan redirecta användaren till lämplig adress. 

[source, ruby, linenums]
.messages#create route i app.rb
----
...
  # messages#create
  post '/messages/' do <1>
  	message = params['content'] <2>
    query = 'INSERT INTO messages (message) VALUES (?) RETURNING *'
    result = db.execute(query, message).first <3>
    redirect "/messages/#{result['id']}" <4>
  end
...
----
<1> Routen för `create` är `/<resursens namn i plural>` med `post` som method.
<2> Hämta ut datan som skickats från `new`-formuläret 
<3> Spara i databasen, och lagra resultatet
<4> Gör en `redirect` till `show` för den nya instansen (eller gör en `redirect` nån annan route)

=== Action: `edit` route: `/messages/:id/edit` method: `get`

`edit` visar ett formulär för att uppdatera en befintlig instans av den aktuella resursen. Eventuellt kan man istället/även visa formuläret på `show` eller någon annanstans.

[source, ruby, linenums]
.messages#edit route i app.rb
----
...
  # messages#new
  get '/messages/:id/edit' do |id| <1>
    @message = db.execute('SELECT * FROM messages WHERE id = ?', id.to_i).first
    erb :'messages/edit' 
  end
...
----
<1> Routen för `edit` är `/<resursens namn i plural>/<resursens id>/edit`.

[source, erb, linenums]
.views/messages/edit.erb
----
<form action='/messages/<%=@message['id']%>/update' method='post'> <1>
  <input type='text' name='content' value='<%= @message['content']%>'></input> <2>
  <button type='submit'>Send</button>
</form>
----
<1> `action` och `method` för `edit`-formuläret motsvarar `update`-routen (se nedan)
<2> `value` "förifyller" input-elementet med datan från backend).

=== Action: `update` route: `/messages/:id/update` method: `post`

`update` är routen edit-formuläret postar datan till. Behöver sedan redirecta användaren till lämplig adress.

[source, ruby, linenums]
.messages#edit route i app.rb
----
...
  # messages#update
  post '/messages/:id/update' do |id| <1>
    message = params['content']
    db.execute('UPDATE messages SET (content = ?) WHERE id = ?', message, id)
    redirect "/messages/#{id}" <2>
  end
...
----
<1> Routen för `update` är `/<resursens namn i plural>/<resursens id>/update` med `post` som method.
<2> Redirect till lämpligt ställe

=== Action: `delete` route: `/messages/:id/delete method: `post

`delete` är routen delete-formuläret postar datan till. Delete-formuläret är antagligen bara ett minimalt formulär runt en knapp och ligger antagligen inte i en egen vy-fil (men kanske i `index.erb` eller `show.erb`):

[source, erb, linenums]
.views/messages/index eller views/messages/show eller annat lämpligt view-fil
----
<form action='/messages/<%= @message['id'] %>/delete' method='post'> <1>
  <button type="submit">DELETE</button>
</form>
----
<1> `action` och `method` för `delete`-formuläret motsvarar `delete`-routen (se nedan)


[source, ruby, linenums]
.messages#delete route i app.rb
----
...
  # messages#delete
  post '/messages/:id/delete' do |id| <1>
    db.execute('DELETE FROM messages WHERE id = ?', id)
		redirect "/messages/"
  end
...
----
<1> Routen för `delete` är `/<resursens namn i plural>/<resursens id>/delete` med `post` som method.

